
source = ~/.config/hypr/themes.conf

general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_in = false
    grace = 5
}

background {
    monitor =
    path = screenshot
    color = $background
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $color4
    inner_color = $color0
    font_color = $foreground
    fade_on_empty = false
    placeholder_text = <i><span foreground="##cdd6f4">Hi, Mark!</span></i>
    hide_input = false
    rounding = 10
    check_color = $color2
    fail_color = $color1
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
}

label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='$color15'>$(date +"%H:%M")</span>"
    color = $color4
    font_size = 90
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='$color6'>$(date +"%A, %B %d")</span>"
    color = $color4
    font_size = 25
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -100
    halign = center
    valign = center
}
