$background = rgba(1e1e2eaa)
$foreground = rgba(cdd6f4ff)

$color0 = rgba(45475aee)
$color1 = rgba(f38ba8ff)
$color2 = rgba(a6e3a1ff)
$color3 = rgba(f9e2afff)
$color4 = rgba(89b4faff)
$color5 = rgba(b4befeff)
$color6 = rgba(94e2d5ff)
$color7 = rgba(a6adc8ff)

$color8 = rgba(585b70ff)
$color9 = rgba(f38ba8ff)
$color10 = rgba(a6e3a1ff)
$color11 = rgba(f9e2afff)
$color12 = rgba(89b4faff)
$color13 = rgba(b4befeff)
$color14 = rgba(94e2d5ff)
$color15 = rgba(a6adc8ff)
